PersistantData = 
{ 
  StrikeGroups = {}, 
    Squadrons = 
      { 
			  { 
            type = "Vgr_mothership", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
				}, 
        { 
            type = "Vgr_commandfortress", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
				},				
				{ 
            type = "Vgr_shipyard", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
				},
				{ 
            type = "Vgr_battlecarrier", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
				},
				{ 
            type = "Vgr_cruiser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 6,
				},
				{ 
            type = "Vgr_pulsedestroyer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 6,
				},
				{ 
            type = "Vgr_destroyer", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 6,
				},
				{ 
            type = "Vgr_LightCruiser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 6,
				},
				{ 
            type = "Vgr_ArtilleryShip", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 6,
				},
				{ 
            type = "Vgr_alkhalid", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1, 
						number = 2,
				},
				{ 
            type = "Vgr_striker", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,	
				},		 
        { 
            type = "Vgr_EliteFighter", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,							
				},
				{ 
            type = "Vgr_missilebomber", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,							
				},
				{ 
            type = "Vgr_AdvAssaultFrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,							
				},
				{ 
            type = "Vgr_SupportFrigate_laser", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,							
				},
				{ 
            type = "Vgr_LongRangeArtilleryFrigate", 
            subsystems = {}, 
            shiphold = {}, 
            name = "", 
            size = 1,
            number = 6,							
				},
				
				
      },        
	Research = {},
}