UnitCapInfoPopup1Width = 200
MAXHEIGHT = 325
PROGRESSBGCOLOR = { 70, 74, 85, 190 }
SHIPQUEUECOLOR = { 246, 212, 0, 255 }

UnitCapInfoPopup1 = {


	maxColor = { 255, 255, 255, 255 }, -- color for max pop reached
	availColor = { 255, 255, 255, 255 }, -- color for pop available

	size = { 2, 71, 100, 200 },

	RootElementSettings = {
		autosize = 1,
	},

	onShow = "UI_HideScreen('BuildQueueMenu'); UI_HideScreen('UnitCapInfoPopup'); UI_HideScreen('YearMenu'); UI_HideScreen('EnergyMenu'); UI_SetButtonPressed('ResourceMenu', 'iconyear1', 1); UI_SetButtonPressed('ResourceMenu', 'iconyear2', 1); UI_SetButtonPressed('NewTaskbar', 'btnRM', 1)",
	onHide = "UI_SetButtonPressed('ResourceMenu', 'iconyear1', 0); UI_SetButtonPressed('ResourceMenu', 'iconyear2', 0); UI_SetButtonPressed('NewTaskbar', 'btnRM', 0)",

	stylesheet = "HW2StyleSheet",

	-- Flags
	pixelUVCoords = 1, -- Enter pixel coords for texture coords

	clickThrough = 1,
	onShow = "UI_SetButtonPressed('NewTaskbar', 'btnRM', 1)",
	onHide = "UI_SetButtonPressed('NewTaskbar', 'btnRM', 0)";

	-- Tab spacer frame to clone
	{
		type = "Frame",
		name = "frmTabSpacer",
		size = { 10, 15 },
		giveParentMouseInput = 1,
	},

	-- Title to clone
	{
		type = "TextLabel",
		name = "lblNameToClone",
		position = { 4, 0 },
		size = { UnitCapInfoPopup1Width - 16, 15 },
		Text = {
			textStyle = "IGHeading2",
		},
		giveParentMouseInput = 1,
		dropShadow = 1,
		visible = 0,
	},

	-- Unit cap item to clone
	{
		type = "Frame",
		name = "frmItemToClone",
		autosize = 1,
		giveParentMouseInput = 1,
		visible = 0;

		{
			type = "Frame",
			name = "frmName",
			position = { 4, 0 },
			size = { UnitCapInfoPopup1Width - 50, 12 },
			autoarrange = 1,
			autoarrangeWidth = 300, -- this is needed b/c of spacers
			visible = 0;
		},


		{
			type = "TextLabel",
			name = "lblUnitCap",
			position = { UnitCapInfoPopup1Width - 46, 0 },
			size = { 45, 12 },
			Text = {
				font = "ATISmallFont",
				color = { 255, 255, 255, 255 },
				hAlign = "Right",
				vAlign = "Middle",
				text = "",
				--text = "<c %06x>%d</c>",
				offset = { -6, 0 },
			},
			giveParentMouseInput = 1,
			--dropShadow = 1,
			visible = 0,
		},
	},

	{
		type = "Frame",
		--position = {2,17},
		autosize = 1,
		--backgroundColor = "IGColorBackground1",
		giveParentMouseInput = 1,
		autoarrange = 1,
		autoarrangeWidth = UnitCapInfoPopup1Width,
		maxSize = { UnitCapInfoPopup1Width, MAXHEIGHT },
		visible = 0;

		-- Frame to hold all unit caps
		{
			type = "Frame",
			name = "frmItems",
			autosize = 1,
			autoarrange = 1,
			autoarrangeWidth = UnitCapInfoPopup1Width,
			giveParentMouseInput = 1,
			visible = 0,
		},

	},

	---INTESTAZIONE-----------------------------------------------------
	{
		type = "Frame",
		position = { 3, 0 },
		size = { 110, 298 };
		{
			type = "TextLabel",
			position = { 15, 0 },
			size = { 85, 13 },
			Text = {
				text = "MONITOR",
				textStyle = "IGHeading2",
				--hAlign = "Center",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 15, 10 },
			size = { 85, 13 },
			name = "ComputerSpy",
			Text = {
				textStyle = "IGHeading2",
				--hAlign = "Center",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 15, 23 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\computerlink.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "Frame",
			position = { 0, 65 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\degree_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 65 },
			size = { 85, 13 },
			Text = {
				text = "Military Rank",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 80 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\honor_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 80 },
			size = { 85, 13 },
			Text = {
				text = "Honour",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 95 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\crew_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 95 },
			size = { 85, 13 },
			Text = {
				text = "Crew",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 110 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\officer_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 110 },
			size = { 85, 13 },
			Text = {
				text = "Officers",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 125 },
			size = { 13, 13 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\lightning_yellow.mres",
				textureUV = { 0, 4, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 125 },
			size = { 85, 13 },
			Text = {
				text = "Energy",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 125 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\tech.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 125 + 15 },
			size = { 85, 13 },
			Text = {
				text = "Research Score",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 140 + 15 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\maintenance_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 140 + 15 },
			size = { 85, 13 },
			Text = {
				text = "Maintenance",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 155 + 15 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\fleet_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 155 + 15 },
			size = { 85, 13 },
			Text = {
				text = "Fleet",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 170 + 15 },
			size = { 12, 12 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\ingameicons\\ru_icon.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 170 + 15 },
			size = { 85, 13 },
			Text = {
				text = "RUs",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 185 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\fusion.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 185 + 15 },
			size = { 85, 13 },
			Text = {
				text = "RU by Fusion",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 200 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\fusion2.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 200 + 15 },
			size = { 85, 13 },
			Text = {
				text = "RU by Trade",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 215 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\fusion1.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 215 + 15 },
			size = { 85, 13 },
			Text = {
				text = "RU by Mining Base",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 230 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\fusion3.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 230 + 15 },
			size = { 85, 13 },
			Text = {
				text = "RU by Population",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "Frame",
			position = { 0, 245 + 15 },
			size = { 16, 16 },
			BackgroundGraphic = {
				texture = "data:ui\\newui\\research\\icons\\diplomacy.mres",
				textureUV = { 0, 0, 13, 13 },
				color = OUTLINECOLOR,
			},
		},
		{
			type = "TextLabel",
			position = { 15, 245 + 15 },
			size = { 85, 13 },
			Text = {
				text = "Diplomacy Fee",
				textStyle = "IGHeading2",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 15, 263 + 15 },
			size = { 85, 13 },
			Text = {
				text = "SCORE",
				textStyle = "IGHeading1",
				offset = { 0, 0 },
				color = "FEColorHeading2",
			},
		},
	},
	---PLAYER 1------------------------------
	{
		type = "Frame",
		position = { 112, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore0",
			Text = {
				textStyle = "IGHeading3",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy0",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore0",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},
	---PLAYER 2------------------------------
	{
		type = "Frame",
		position = { 191, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy1",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore1",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},
	---PLAYER 3------------------------------
	{
		type = "Frame",
		position = { 269, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy2",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore2",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},
	---PLAYER 4------------------------------
	{
		type = "Frame",
		position = { 347, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy3",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore3",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},
	---PLAYER 5------------------------------
	{
		type = "Frame",
		position = { 425, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy4",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore4",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},
	---PLAYER 6------------------------------
	{
		type = "Frame",
		position = { 503, 0 },
		size = { 78, 298 };
		{
			type = "TextLabel",
			position = { 0, 0 },
			size = { 75, 13 },
			name = "lblPopUnitsStaticText5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 23, 0 },
			size = { 45, 13 },
			name = "isai5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 15 },
			size = { 75, 13 },
			name = "lblname5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 30 },
			size = { 75, 13 },
			name = "diplomazia5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatus5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 45 },
			size = { 75, 13 },
			name = "lblstatusp5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = { 255, 0, 0, 170 },
			},
		},
		{
			type = "TextLabel",
			position = { 0, 65 },
			size = { 75, 13 },
			name = "lblgrado5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 80 },
			size = { 75, 13 },
			name = "lblhonor5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 95 },
			size = { 75, 13 },
			name = "lblPopUnits5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsb5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 12, 95 },
			size = { 75, 13 },
			name = "lblPopUnitsbr5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnits5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsb5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 6, 110 },
			size = { 75, 13 },
			name = "lblPopOfficerUnitsbr5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 },
			size = { 75, 13 },
			name = "energy5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 125 + 15 },
			size = { 75, 13 },
			name = "lbltotalscore5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 140 + 15 },
			size = { 75, 13 },
			name = "lblMaintenance5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 170 + 15 },
			size = { 75, 13 },
			name = "lblResourceUnits5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 155 + 15 },
			size = { 75, 13 },
			name = "fleet5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 185 + 15 },
			size = { 75, 13 },
			name = "lblFusion5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 200 + 15 },
			size = { 75, 13 },
			name = "lbltrade5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 215 + 15 },
			size = { 75, 13 },
			name = "lblmegalith5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 230 + 15 },
			size = { 75, 13 },
			name = "lblplanet5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 245 + 15 },
			size = { 75, 13 },
			name = "diplomacy5",
			Text = {
				textStyle = "IGHeading2",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
		{
			type = "TextLabel",
			position = { 0, 263 + 15 },
			size = { 75, 13 },
			name = "lblscore5",
			Text = {
				textStyle = "IGHeading1",
				hAlign = "Left",
				offset = { 0, 0 },
				color = "FEColorHeading3",
			},
		},
	},

}
