fx = {
    style = "STYLE_COMBO",
    properties = {
        property_06 = {
            name = "FX7",
            type = "VARTYPE_STRING",
            value = "pulsar_muzzle_tipdrone", },
        property_05 = {
            name = "FX6",
            type = "VARTYPE_STRING",
            value = "pulsar_muzzle_flash_ringdrone", },
        property_07 = {
            name = "FX8",
            type = "VARTYPE_STRING",
            value = "", },
        property_02 = {
            name = "FX3",
            type = "VARTYPE_STRING",
            value = "PULSAR_PULSE_BEAMdrone", },
        property_01 = {
            name = "Fx2",
            type = "VARTYPE_STRING",
            value = "pulsar_laser_squirtdrone", },
        property_04 = {
            name = "FX5",
            type = "VARTYPE_STRING",
            value = "", },
        property_03 = {
            name = "FX4",
            type = "VARTYPE_STRING",
            value = "PLASMA_FLASH_LIGHTdrone", },
        property_00 = {
            name = "Fx1",
            type = "VARTYPE_STRING",
            value = "", }, }, }
