TRUE = 1
FALSE = 0
BitRate = 16
OutputChannels = 2
SampleRate = 44100
ProviderHW3D = "DirectSound3D Hardware Support"
ChannelsHW3D = 16
ResChanHW3D = 2
ProviderSW3D = "DirectSound3D Software Emulation"
ChannelsSW3D = 16
ResChanSW3D = 2
Provider2D = "2D"
Channels2D = 8
ResChan2D = 2
ProviderSTRM = "Streaming"
ChannelsSTRM = 6
ResChanSTRM = 2
SoundDriver = "FDAudio"
DefaultFilter = "Reverb3 Filter"
DefaultEnvType = 18
