type = "TRAIL"
radius = 6
scarProbability = 1
shallowAngleDeg = 80
minScarDist = 9
minExtendDist = 6
maxExtendDist = 12
batchRender = 1
dashOverDot = 0
dotTextures = { "burn_dot.tga", }
dashTextures = { "burn_dash.tga", }
fxProbability = 0.05
fxs = { "smoke_loop_spray", }
transitionFXs = {}
