aitrace("CPU: CLASSDEF LOADED")
squadclass = {}
squadclass[eMotherShip] = {
	HGN_MOTHERSHIP,	
	VGR_MOTHERSHIP,	
}
squadclass[eCollector] = {
	HGN_RESOURCECOLLECTOR,	
	VGR_RESOURCECOLLECTOR,
}
squadclass[eScout] = {
	HGN_SCOUT,
	HGN_PROBE,
	HGN_PROXIMITYSENSOR,
	HGN_ECMPROBE,
	HGN_GHOST,
	HGN_DEFENDER,	
	VGR_SCOUT,
	VGR_PROBE,
	VGR_PROBE_SMALLHSBEACON,
  VGR_GHOST,	
	VGR_PROBE_PROX,
	VGR_PROBE_ECM,
}
squadclass[eRefinery] = {
	HGN_RESOURCECONTROLLER,	
	HGN_SCAVER, 
	VGR_RESOURCECONTROLLER,
	VGR_RESOURCECONTROLLERDOUBLE,
	VGR_SCAVER, 
}
squadclass[eBuilder] = {
	HGN_MOTHERSHIP,
	HGN_CARRIER,
	HGN_BATTLECARRIER,
	HGN_LIGHTCARRIER,   	
	HGN_SHIPYARD,	
  HGN_BATTLESHIPYARD,	
  HGN_RESEARCHSTATION,
	HGN_COMBATBASE,
	HGN_POWER,
	HGN_CREWSTATION,		
	VGR_MOTHERSHIP,	
	VGR_CARRIER,  
	VGR_LIGHTCARRIER,
	VGR_BATTLECARRIER, 
	VGR_SHIPYARD,
}
squadclass[eDropOff] = {
	HGN_MOTHERSHIP,
	HGN_CARRIER,  
	HGN_BATTLECARRIER,
	HGN_SHIPYARD,
	HGN_BATTLESHIPYARD,	
	HGN_RESOURCECONTROLLER,	
	HGN_SCAVER, 		
	VGR_MOTHERSHIP,	
	VGR_CARRIER,  
	VGR_LIGHTCARRIER,  
	VGR_SHIPYARD,
	VGR_RESOURCECONTROLLER,
	VGR_RESOURCECONTROLLERDOUBLE,			
	VGR_SCAVER, 
}
squadclass[eSalvageDropOff] = {
  HGN_MOTHERSHIP,
	HGN_CARRIER,
	HGN_BATTLECARRIER,
	HGN_SHIPYARD,	
	HGN_BATTLESHIPYARD,	
	HGN_SCAVER, 
	HGN_COMMANDFORTRESS,
	HGN_BATTLESTATION,
	VGR_MOTHERSHIP,	
	VGR_CARRIER,  
	VGR_LIGHTCARRIER,
	VGR_SHIPYARD,
	VGR_COMMANDFORTRESS,
	VGR_SCAVER, 
}
squadclass[eFighter] = {
	HGN_INTERCEPTOR,
	HGN_ATTACKBOMBER,	
	HGN_RAILGUNFIGHTER,
	HGN_LBOMBER,
	HGN_HFT,	
	HGN_ATTACKBOMBERHEAVY,		
	VGR_INTERCEPTOR,
	VGR_BOMBER,
	VGR_MISSILEBOMBER,
	VGR_LANCEFIGHTER,
	VGR_HEAVYFIGHTER,
	VGR_ELITEFIGHTER,
	VGR_DEFENDER,
}
squadclass[eCorvette] = {
	HGN_ASSAULTCORVETTE,
	HGN_PULSARCORVETTE,
	HGN_BOMBERVETTE,
	HGN_EMPCORVETTE,
	HGN_MINELAYERCORVETTE,
	HGN_MULTIGUNCORVETTE,
	HGN_CTH,
	HGN_CTHION,	
	VGR_MISSILECORVETTE,	
	VGR_SHAMSHIRIICTG,
	VGR_LASERCORVETTE,
	VGR_PLASMACORVETTE,
	VGR_EMPCORVETTE,
	VGR_MINELAYERCORVETTE,
	VGR_COMMANDCORVETTE,
	VGR_MULTILANCECORVETTE,
	VGR_MORTARCORVETTE,
	VGR_STRIKER,
	VGR_STANDVETTE,
}
squadclass[eFrigate] = {
	HGN_ASSAULTFRIGATE,
	HGN_DEFENSEFIELDFRIGATE,
	HGN_IONCANNONFRIGATE,
	HGN_MARINEFRIGATE,
	HGN_MARINEFRIGATE_SOBAN,
	HGN_TORPEDOFRIGATE,
	HGN_TORPEDOFRIGATEELITE,
	HGN_LRMS,	
	HGN_TULWAR,
	VGR_ASSAULTFRIGATE,
	VGR_ADVASSAULTFRIGATE,
	VGR_HEAVYMISSILEFRIGATE,
	VGR_SUPPORTFRIGATE,
	VGR_COMMANDFRIGATE,
	VGR_SUPPORTFRIGATE_LASER,
	VGR_SUPPORTFRIGATEARMED,
	VGR_INFILTRATORFRIGATE,
	VGR_ARTILLERYFRIGATE,
	VGR_EMPFRIGATE,	
	VGR_LONGRANGEARTILLERYFRIGATE,	
}
squadclass[eCapture] = {
	HGN_MARINEFRIGATE,	
	VGR_INFILTRATORFRIGATE,
}
squadclass[eShield] = {
	HGN_DEFENSEFIELDFRIGATE,
	VGR_AM,	
}
squadclass[ePlatform] = {
	HGN_GUNTURRET,
  HGN_PULSARTURRET,
	HGN_IONTURRET,	
	HGN_MISSILETURRET,
	HGN_RTS,	
	HGN_ARTILLERYSENTINEL,		
	HGN_MASSIVETURRET,	
	VGR_WEAPONPLATFORM_GUN,
	VGR_WEAPONPLATFORM_LANCE,
	VGR_WEAPONPLATFORM_MISSILE,
	VGR_HYPERSPACE_PLATFORM,  
}
squadclass[eAntiFighter] = {
	HGN_INTERCEPTOR,
	HGN_ASSAULTCORVETTE,
	HGN_MULTIGUNCORVETTE,
	HGN_ASSAULTFRIGATE,
	HGN_GUNTURRET,  	    
	HGN_HFT,	
	HGN_CTH,		
	HGN_SWEEPERDESTROYER,
	VGR_INTERCEPTOR,
	VGR_DEFENDER,	
	VGR_ELITEFIGHTER,
	VGR_STANDVETTE,
	VGR_ASSAULTFRIGATE,
	VGR_ADVASSAULTFRIGATE,
	VGR_WEAPONPLATFORM_GUN,
}
squadclass[eAntiCorvette] = {
  HGN_RAILGUNFIGHTER, 
  HGN_HFT,  
	HGN_PULSARCORVETTE,
	HGN_MULTIGUNCORVETTE,
	HGN_CTH,			
	HGN_ASSAULTFRIGATE,
	HGN_TORPEDOFRIGATE,	
	HGN_DESTROYER,
	HGN_SWEEPERDESTROYER,
	HGN_JUGGERNAUGHT,
	HGN_GUNTURRET,
  HGN_PULSARTURRET,	    
  HGN_TULWAR,
	VGR_LANCEFIGHTER,
	VGR_HEAVYFIGHTER,
	VGR_ELITEFIGHTER,
	VGR_LASERCORVETTE,
	VGR_PLASMACORVETTE,
	VGR_MULTILANCECORVETTE,	
	VGR_STANDVETTE,
	VGR_STRIKER,
	VGR_DESTROYER,	
	VGR_ASSAULTFRIGATE,
	VGR_ADVASSAULTFRIGATE,
	VGR_WEAPONPLATFORM_GUN,
	VGR_WEAPONPLATFORM_LANCE,
}
squadclass[eAntiFrigate] = {
  HGN_RAILGUNFIGHTER, 
	HGN_ATTACKBOMBER,
	HGN_ATTACKBOMBERHEAVY,
	HGN_CTHION,		
	HGN_BOMBERVETTE,		
	HGN_IONCANNONFRIGATE,
	HGN_MARINEFRIGATE,	
	HGN_DEFENSEFIELDFRIGATE,
	HGN_LRMS,
	HGN_TULWAR,
	HGN_DESTROYER,	
	HGN_MISSILEDESTROYER,
	HGN_IONDESTROYER,	
	HGN_ADVDESTROYER,
	HGN_ARTILLERYDESTROYER,
	HGN_CRUISERA,
	HGN_CRUISERB,
	HGN_JUGGERNAUGHT,
	HGN_BATTLECRUISER,
	HGN_BATTLESHIP,
	HGN_VORTEX,	
	HGN_IONTURRET, 
	HGN_MISSILETURRET,
	HGN_RTS,	
	HGN_ARTILLERYSENTINEL,
	HGN_MASSIVETURRET,				
	HGN_COMMANDFORTRESS,
	HGN_ARK,
	VGR_COMMANDFORTRESS,	
	VGR_BOMBER,
	VGR_MISSILEBOMBER,
	VGR_HEAVYFIGHTER,
	VGR_ELITEFIGHTER,
	VGR_HEAVYMISSILEFRIGATE,
	VGR_SUPPORTFRIGATE,
	VGR_SUPPORTFRIGATE_LASER,
	VGR_SUPPORTFRIGATEARMED,
	VGR_INFILTRATORFRIGATE,
	VGR_STRIKER,
	VGR_EMPFRIGATE,
	VGR_MULTILANCECORVETTE,
	VGR_MORTARCORVETTE,
	VGR_DESTROYER,
	VGR_PULSEDESTROYER,
	VGR_AM,
	VGR_CRUISER,
	VGR_LIGHTCRUISER,
	VGR_ARTILLERYSHIP,
	VGR_SINNER,
	VGR_BATTLECRUISER,
	VGR_MISSILEBATTLECRUISER,
	VGR_ALKHALID,
	VGR_DREADNAUGHT,
	VGR_WEAPONPLATFORM_MISSILE,	
}
squadclass[eCapital] = {
	HGN_CARRIER,
	HGN_BATTLECARRIER,
	HGN_LIGHTCARRIER,    
	HGN_RESEARCHSTATION,
	HGN_COMBATBASE,
	HGN_POWER,
	HGN_CREWSTATION,	
	HGN_MOTHERSHIP,
	HGN_SHIPYARD,
	HGN_BATTLESHIPYARD,	
	HGN_DESTROYER,
	HGN_SWEEPERDESTROYER,
	HGN_MISSILEDESTROYER,
	HGN_IONDESTROYER,
	HGN_ADVDESTROYER,
	HGN_ARTILLERYDESTROYER,
	HGN_CRUISERA,
	HGN_CRUISERB,
	HGN_JUGGERNAUGHT,
	HGN_BATTLECRUISER,
	HGN_BATTLESHIP,
	HGN_VORTEX,	
	HGN_TANKER,
	HGN_LIGHTTANKER,	
	HGN_COMMANDFORTRESS,
	HGN_BATTLESTATION,
	HGN_ARK,	
	HGN_HYPERSPACESTATION,	
	VGR_COMMANDFORTRESS,
	VGR_CARRIER,  
	VGR_LIGHTCARRIER,
	VGR_BATTLECARRIER, 
	VGR_MOTHERSHIP,	
	VGR_SHIPYARD,
	VGR_DESTROYER,	
	VGR_PULSEDESTROYER,
	VGR_CRUISER,
	VGR_LIGHTCRUISER,
	VGR_ARTILLERYSHIP,
	VGR_AM,
	VGR_SINNER,
	VGR_BATTLECRUISER,
	VGR_MISSILEBATTLECRUISER,
	VGR_ALKHALID,
	VGR_DREADNAUGHT,	
}
squadclass[eNonThreat] = {
	HGN_RESOURCECOLLECTOR,
	VGR_RESOURCECOLLECTOR,
	HGN_RESOURCECONTROLLER,
	VGR_RESOURCECONTROLLER,	
	VGR_RESOURCECONTROLLERDOUBLE,
	HGN_CARRIER,	
	HGN_LIGHTCARRIER,    
	HGN_RESEARCHSTATION,
	HGN_POWER,
	HGN_CREWSTATION,
	HGN_MOTHERSHIP,
	HGN_SHIPYARD,
	VGR_CARRIER,  
	VGR_LIGHTCARRIER,
	VGR_MOTHERSHIP,	
	VGR_SHIPYARD,	
	HGN_SCOUT,
	HGN_PROBE,
	HGN_GHOST,
	HGN_PROXIMITYSENSOR,
	HGN_ECMPROBE,
	HGN_DEFENDER,			
	HGN_TRANSPORTCELL,	
	VGR_SCOUT,
	VGR_PROBE,
	VGR_PROBE_SMALLHSBEACON,	
	VGR_PROBE_PROX,
	VGR_PROBE_ECM,	
	VGR_HYPERSPACE_PLATFORM,
}
squadclass[eHyperspaceGate] = 
{
	VGR_HYPERSPACE_PLATFORM,
	HGN_HYPERSPACESTATION,
}
squadclass[eSubSystemAttackers] = 
{
	HGN_ATTACKBOMBER,
	HGN_ATTACKBOMBERHEAVY,
	HGN_LBOMBER,	
	VGR_BOMBER,
	VGR_MISSILEBOMBER,
	VGR_ELITEFIGHTER,
}
squadclass[eNonCriticalSubSys] = 
{	
	HARVESTCONTROLMODULE,
	FUSION,
	DRIVESYSTEM,
	FIRECONTROLTOWER,
	DEFENSEFIELDMODULE,
	BUILD,
	REPAIRSYSTEM,	
	CLOAKGENERATOR,		
	HOLESCRUMBLER,  
	ADVANCEDARRAY,
	CLOAKSENSOR,
	HYPERSPACESENSOR,
}
squadclass[eGoodRepairAttackers] = 
{
	HGN_INTERCEPTOR,
	HGN_RAILGUNFIGHTER,
	HGN_HFT,	
	HGN_ASSAULTCORVETTE,
	HGN_PULSARCORVETTE,
	HGN_MULTIGUNCORVETTE,
	HGN_CTH,	
	VGR_INTERCEPTOR,
	VGR_LANCEFIGHTER,
	VGR_DEFENDER,
	VGR_HEAVYFIGHTER,
	VGR_ELITEFIGHTER,
	VGR_MISSILECORVETTE,
	VGR_MULTILANCECORVETTE,	
	VGR_MORTARCORVETTE,
	VGR_STRIKER,		
	VGR_STANDVETTE,	
}
eUselessShips = eMaxCount
eBattleCruiser = eMaxCount + 1
sg_maxClasses = eBattleCruiser + 1
squadclass[ eUselessShips ] = 
{
	HGN_MINELAYERCORVETTE,	
	VGR_MINELAYERCORVETTE,
	VGR_COMMANDCORVETTE,
}
squadclass[eBattleCruiser] = 
{
	HGN_BATTLECRUISER,
  VGR_MISSILEBATTLECRUISER,	
	HGN_VORTEX,
	HGN_BATTLESHIP,
	VGR_SINNER,
	VGR_BATTLECRUISER,
	VGR_ALKHALID,
	VGR_DREADNAUGHT,
	VGR_BATTLECARRIER,
}

function FastAddToClass( tbl, classid )
	for a,b in tbl do
		AddToClass( b, classid )
	end
end

function ClassInitialize()
	for i=0, sg_maxClasses do
		if (squadclass[i]) then
			FastAddToClass( squadclass[i], i )
		end
	end		
	AddClassName( eMotherShip, "Motherships")
	AddClassName( eCollector, "Collectors")
	AddClassName( eDropOff, "DropOffs")
	AddClassName( eFighter, "Fighters")
	AddClassName( eFrigate, "Frigates")
	AddClassName( eCorvette, "Corvettes")
	AddClassName( eCapital, "Capital")
	AddClassName( eAntiFighter, "AntiFighter")
	AddClassName( eAntiCorvette, "AntiCorvette")
	AddClassName( eAntiFrigate, "AntiFrigate")
	AddClassName( ePlatform, "Platform")
	AddClassName( eRefinery, "Refinery")
	AddClassName( eHyperspaceGate, "HypGates")
	AddClassName( eShield, "Shields")
	AddClassName( eCapture, "Capture")
	AddClassName( eSubSystemAttackers, "SubSysKillas")
	AddClassName( eBattleCruiser, "BattleCruiser")		
end