music_data_original = {
	size = 20,
	musics = {
		{
			name = "Ambient 01 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_01",
			minute = 2,
			second = 37,
		},
		{
			name = "Ambient 02 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_02",
			minute = 1,
			second = 50,
		},
		{
			name = "Ambient 03 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_03",
			minute = 2,
			second = 35,
		},
		{
			name = "Ambient 04 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_04",
			minute = 1,
			second = 50,
		},
		{
			name = "Ambient 05 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_05",
			minute = 2,
			second = 9,
		},
		{
			name = "Ambient 06 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_06",
			minute = 1,
			second = 43,
		},
		{
			name = "Ambient 07 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_07",
			minute = 2,
			second = 4,
		},
		{
			name = "Ambient 08 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_08",
			minute = 2,
			second = 21,
		},
		{
			name = "Ambient 12 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_12",
			minute = 1,
			second = 48,
		},
		{
			name = "Ambient 13 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_13",
			minute = 1,
			second = 54,
		},
		{
			name = "Ambient 14 - Homeworld 2",
			path = "Data:sound/music/ambient/amb_14",
			minute = 2,
			second = 25,
		},
		{
			name = "Battle 01 - Homeworld 2",
			path = "Data:sound/music/battle/battle_01",
			minute = 4,
			second = 36,
		},
		{
			name = "Battle 04 - Homeworld 2",
			path = "Data:sound/music/battle/battle_04",
			minute = 3,
			second = 46,
		},
		{
			name = "Battle 04 ALT - Homeworld 2",
			path = "Data:sound/music/battle/battle_04_alt",
			minute = 3,
			second = 0,
		},
		{
			name = "Battle 06 - Homeworld 2",
			path = "Data:sound/music/battle/battle_06",
			minute = 3,
			second = 11,
		},
		{
			name = "Battle Keeper - Homeworld 2",
			path = "Data:sound/music/battle/battle_keeper",
			minute = 2,
			second = 57,
		},
		{
			name = "Battle Movers - Homeworld 2",
			path = "Data:sound/music/battle/battle_movers",
			minute = 2,
			second = 38,
		},
		{
			name = "Battle PlanetKillers - Homeworld 2",
			path = "Data:sound/music/battle/battle_planetkillers",
			minute = 3,
			second = 7,
		},
		{
			name = "Battle Sajuuk - Homeworld 2",
			path = "Data:sound/music/battle/battle_sajuuk",
			minute = 2,
			second = 41,
		},
		{
			name = "Battle Arrival - Homeworld 2",
			path = "Data:sound/music/battle/bentus_arrival",
			minute = 1,
			second = 4,
		},
	},
}
