UC_Family("Complex", 100);
UC_Family("Stop", 0);

UC_Family("Fighter", 100);
UC_Family("Corvette", 100);
UC_Family("Frigate", 100);
UC_Family("Capital", 100);
UC_Family("Mothership",1);
UC_Family("SinglePlayerMisc", 100);
UC_Family("Platform", 100);
UC_Family("Utility", 100);

UC_ShipType("ResourceCollector", 100);
UC_ShipType("ResourceController", 100);  

UC_ShipType("crewstation", 1);
UC_ShipType("researchstation", 1);
UC_ShipType("powerstation", 1);
UC_ShipType("weaponstation", 1);
UC_ShipType("Core", 1);
UC_ShipType("TangoMine", 9);
UC_ShipType("ViperMissile", 3);
UC_ShipType("ViperMissile_ws", 3);
UC_ShipType("ViperMissile_ws1", 3);
UC_ShipType("Patcher", 18);
UC_ShipType("Drone", 18);
UC_ShipType("MassiveTurret", 9);
UC_ShipType("CruseMissile", 3);
UC_ShipType("TradeContainer", 18);
UC_ShipType("NuclearTube1", 3);
UC_ShipType("NuclearTube2", 3);
UC_ShipType("NuclearTube3", 3);
UC_ShipType("NuclearBomb", 3);
UC_ShipType("Boa", 9);
UC_ShipType("Shipyard", 1);
UC_ShipType("massshield_1", 1);
UC_ShipType("massshield_2", 1);
UC_ShipType("massshield_3", 1);
UC_ShipType("massshield_4", 1);
UC_ShipType("massshield_5", 1);
UC_ShipType("massshield_6", 1);